data:
    root_folder: 'dataset/1024_512'
    img_size: (512,512)
    test_folder: '/mnt/data/RasterMask_v11/test_images'
model:
    backbone_name: 'openmmlab/upernet-swin-tiny'
training:
    lr: 0.0001
    weight_decay: 0.00001
    gradient_clip_val: 25.0
    accumulate_grad_batches: 1